version: "3.7"
services:
  fatura_any:
    image: marcelogbjunior/fatura-anymarket:0.0.3
    container_name: fatura_any_container
    environment:
      - NERUS_MYSQL_USER=
      - NERUS_MYSQL_PSWD=
      - NERUS_MYSQL_IP=
      - NERUS_MYSQL_PORT=
      - NERUS_DBSQL=
    ports:
      - 3014
    volumes:
      - ".:/web"
    restart: always