version: "3.7"
services:
  fatura_any:
    image: marcelogbjunior/fatura-anymarket:0.0.7
    network_mode: "host"
    container_name: fatura_any_container
    environment:
      - DB_HOST=
      - DB_PORT=3306
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
    ports:
      - 3014
    volumes:
      - ".:/web"
    restart: always